# Generated by Django 4.1.7 on 2023-06-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account', models.CharField(max_length=40, verbose_name='客户账号')),
                ('customer_full_name', models.CharField(max_length=80, null=True, verbose_name='客户全名')),
                ('customer_rate', models.FloatField(null=True, verbose_name='客户费率')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'unique_together': {('customer_account', 'customer_rate')},
            },
        ),
        migrations.CreateModel(
            name='LandlineNumber',
            fields=[
                ('number', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='号码')),
                ('actual_number', models.CharField(max_length=40, verbose_name='实号码')),
                ('province', models.CharField(max_length=40, verbose_name='省份')),
                ('area', models.CharField(max_length=40, verbose_name='地区')),
                ('carrier', models.CharField(max_length=40, verbose_name='运营商')),
                ('supplier', models.CharField(max_length=40, verbose_name='供应商')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '固话号码',
                'verbose_name_plural': '固话号码',
            },
        ),
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('number', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='号码')),
                ('province', models.CharField(max_length=40, verbose_name='省份')),
                ('area', models.CharField(max_length=40, verbose_name='地区')),
                ('prefix', models.CharField(max_length=40, verbose_name='前缀')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '手机号码',
                'verbose_name_plural': '手机号码',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=40, verbose_name='业务名称')),
                ('business_full_name', models.CharField(max_length=40, null=True, verbose_name='业务全名')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '业务',
                'verbose_name_plural': '业务',
                'unique_together': {('customer', 'business_name')},
            },
        ),
        migrations.CreateModel(
            name='MobileNumberAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.business', verbose_name='业务')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.customer', verbose_name='客户')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.mobilenumber', verbose_name='手机号码')),
            ],
            options={
                'verbose_name': '手机号码分配',
                'verbose_name_plural': '手机号码分配',
                'unique_together': {('business', 'number')},
            },
        ),
        migrations.CreateModel(
            name='LandlineNumberAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.business', verbose_name='业务')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.customer', verbose_name='客户')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.landlinenumber', verbose_name='固话号码')),
            ],
            options={
                'verbose_name': '固话号码分配',
                'verbose_name_plural': '固话号码分配',
                'unique_together': {('business', 'number')},
            },
        ),
    ]
