# Generated by Django 4.2.2 on 2023-06-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCode',
            fields=[
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('area', models.CharField(max_length=20, verbose_name='地区')),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='区号')),
            ],
            options={
                'verbose_name': '区号省市',
                'verbose_name_plural': '区号省市',
                'db_table': 'manage_app_area_code',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account', models.CharField(max_length=40, verbose_name='客户账号')),
                ('customer_full_name', models.CharField(max_length=80, null=True, verbose_name='客户全名')),
                ('customer_rate', models.FloatField(null=True, verbose_name='客户费率')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'managed': True,
                'unique_together': {('customer_account', 'customer_rate')},
            },
        ),
        migrations.CreateModel(
            name='LandlineNumber',
            fields=[
                ('number', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='号码')),
                ('actual_number', models.CharField(max_length=40, verbose_name='实号码')),
                ('province', models.CharField(max_length=40, verbose_name='省份')),
                ('area', models.CharField(max_length=40, verbose_name='地区')),
                ('area_code', models.IntegerField(default=None, verbose_name='区号')),
                ('carrier', models.CharField(max_length=40, verbose_name='运营商')),
                ('supplier', models.CharField(max_length=40, verbose_name='供应商')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下号时间')),
                ('inbound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_app.customer', verbose_name='呼入客户')),
            ],
            options={
                'verbose_name': '固话号码',
                'verbose_name_plural': '固话号码',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('number', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='号码')),
                ('province', models.CharField(max_length=40, verbose_name='省份')),
                ('area', models.CharField(max_length=40, verbose_name='地区')),
                ('area_code', models.IntegerField(default=None, verbose_name='区号')),
                ('prefix', models.CharField(max_length=40, verbose_name='前缀')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下号时间')),
                ('inbound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_app.customer', verbose_name='呼入客户')),
            ],
            options={
                'verbose_name': '手机号码',
                'verbose_name_plural': '手机号码',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MobilePrefix',
            fields=[
                ('prefix', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='手机号段')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('area', models.CharField(max_length=20, verbose_name='地区')),
                ('code', models.IntegerField(verbose_name='区号')),
            ],
            options={
                'verbose_name': '手机省市',
                'verbose_name_plural': '手机省市',
                'db_table': 'manage_app_mobile_prefix',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=40, verbose_name='客户-业务')),
                ('business_full_name', models.CharField(max_length=40, null=True, verbose_name='业务全名/备注')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '业务',
                'verbose_name_plural': '业务',
                'managed': True,
                'unique_together': {('customer', 'business_name')},
            },
        ),
        migrations.CreateModel(
            name='MobileNumberAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound', models.BooleanField(default=True, verbose_name='是否呼入')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.business', verbose_name='客户-业务')),
                ('numbers', models.ManyToManyField(to='manage_app.mobilenumber', verbose_name='手机号码')),
            ],
            options={
                'verbose_name': '手机号码分配',
                'verbose_name_plural': '手机号码分配',
                'managed': True,
                'unique_together': {('business',)},
            },
        ),
        migrations.CreateModel(
            name='LandlineNumberAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound', models.BooleanField(default=True, verbose_name='是否呼入')),
                ('isenabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.business', verbose_name='客户-业务')),
                ('numbers', models.ManyToManyField(to='manage_app.landlinenumber', verbose_name='固话号码')),
            ],
            options={
                'verbose_name': '固话号码分配',
                'verbose_name_plural': '固话号码分配',
                'managed': True,
                'unique_together': {('business',)},
            },
        ),
    ]
