# Generated by Django 4.2.2 on 2023-06-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areacode',
            options={'managed': True, 'verbose_name': '区号省市查询表', 'verbose_name_plural': '区号省市查询表'},
        ),
        migrations.AlterModelOptions(
            name='mobileprefix',
            options={'managed': True, 'verbose_name': '手机省市查询表', 'verbose_name_plural': '手机省市查询表'},
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='customer_full_name',
            new_name='supplier_full_name',
        ),
    ]
