# Generated by Django 4.1.7 on 2023-06-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='landlinenumberallocation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mobilenumberallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='landlinenumberallocation',
            name='numbers',
            field=models.ManyToManyField(to='manage_app.landlinenumber', verbose_name='固话号码'),
        ),
        migrations.AddField(
            model_name='mobilenumberallocation',
            name='numbers',
            field=models.ManyToManyField(to='manage_app.mobilenumber', verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_full_name',
            field=models.CharField(max_length=40, null=True, verbose_name='业务全名/备注'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=40, verbose_name='客户-业务'),
        ),
        migrations.AlterField(
            model_name='landlinenumberallocation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.business', verbose_name='客户-业务'),
        ),
        migrations.AlterField(
            model_name='mobilenumberallocation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.business', verbose_name='客户-业务'),
        ),
        migrations.AlterUniqueTogether(
            name='landlinenumberallocation',
            unique_together={('business',)},
        ),
        migrations.AlterUniqueTogether(
            name='mobilenumberallocation',
            unique_together={('business',)},
        ),
        migrations.RemoveField(
            model_name='landlinenumberallocation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='landlinenumberallocation',
            name='number',
        ),
        migrations.RemoveField(
            model_name='mobilenumberallocation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='mobilenumberallocation',
            name='number',
        ),
    ]
