# Generated by Django 4.2.2 on 2023-06-29 10:00

from django.db import migrations, models
import django.db.models.deletion
import manage_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_alter_areacode_options_alter_mobileprefix_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': True, 'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
        migrations.AlterField(
            model_name='landlinenumber',
            name='inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_app.landlinenumberallocation', verbose_name='呼入客户'),
        ),
        migrations.AlterField(
            model_name='landlinenumberallocation',
            name='numbers',
            field=manage_app.models.CustomLandlineNumberField(blank=True, to='manage_app.landlinenumber', verbose_name='固话号码'),
        ),
        migrations.AlterField(
            model_name='mobilenumberallocation',
            name='numbers',
            field=models.ManyToManyField(blank=True, to='manage_app.mobilenumber', verbose_name='手机号码'),
        ),
    ]
