# Generated by Django 4.2.2 on 2023-06-16 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_alter_landlinenumberallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlinenumber',
            name='inbound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_app.customer', verbose_name='呼入客户'),
        ),
        migrations.AddField(
            model_name='mobilenumber',
            name='inbound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_app.customer', verbose_name='呼入客户'),
        ),
        migrations.AlterField(
            model_name='business',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='landlinenumber',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='下号时间'),
        ),
        migrations.AlterField(
            model_name='landlinenumber',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后时间'),
        ),
        migrations.AlterField(
            model_name='landlinenumberallocation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='下号时间'),
        ),
        migrations.AlterField(
            model_name='mobilenumberallocation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
